### PR TITLE
Filter nameless grammars from selection list

### PR DESCRIPTION
**Pull request by Alhadis**
Prior to v1.11, the selector-list omitted from its results any grammars which lack a `name` field. This is desirable, because such grammars [generally exist](https://github.com/github/linguist/pull/3147#issuecomment-238121112) for internal use only:

Figure 1

They've reappeared in the selector results again, which convinces me it might've been a bug instead of a feature. This PR enforces their exclusion specifically, enabling grammar authors a means of hiding "helper" grammars from the end user.

/cc @lierdakil

### CODE REVIEW

**Comment by lierdakil** [comment]
:+1:

I probably should also mention that https://github.com/atom/settings-view/blob/master/lib/package-grammars-view.coffee#L50 needs the similar kind of change, since settings-vew shows nameless grammars as `undefined Grammar`.

Honestly, at this point I'm thinking along the lines of removing those from grammars completely and providing a local instance of `GrammarRegistry` in language-haskell...

**Comment by Alhadis** [comment]
Ah damn, that's a good catch. Never noticed that, actually. Next PR coming up.

And yeah, I'll admit the Haskell package is a bit of an unorthodox case, but the truth of the matter is that there're many packages out there that use "modular" grammars for highlighting complicated content (such as regular expressions).

Then you have [stuff like this](https://github.com/atom/language-hyperlink) and [this](https://github.com/atom/language-todo) which isn't nameless, but should damn well be hidden as a selection choice. I can't imagine how many users were expecting an Atomised Org-mode when they assigned `TODO` as a plain-text checklist's grammar...

**Comment by lierdakil** [comment]
Good point about hyperlink and todo.

**Comment by 50Wliu** [comment]
This looks like it was [actually intentional](https://github.com/atom/grammar-selector/commit/51c531043eaa9e0af6b1eec3e8fa0ca12620471e), though that change was way back in 2014.  Like you said, `name` is optional: therefore there is the possibility that there are some grammars out there that don't actually have a name yet are expected to show up in the grammar selector.

Wouldn't #32 be a better solution (without the config option)?

**Comment by Alhadis** [comment]
No. It's poor UX for a grammar to be listed as `scope.whatever`. Authors should be specifying a name for their grammars in the first place.

**Comment by Alhadis** [comment]
@50Wliu Just curious, has there been any movement with reviewing this PR?

**Comment by 50Wliu** [comment]
No.  I'll put it on the personal backlog since it seems like a small change.

**Comment by 50Wliu** [comment]
Ok.  I think that it makes sense for grammars that are missing either the `name` field or have no `fileTypes` set to not appear in the grammar selector.  This way TODO and hyperlink are hidden as well.

**Comment by Alhadis** [comment]
> This way TODO and hyperlink are hidden as well.

Heh. Yeah, I still remember how confused I was the first time I saw them listed in the languages list. Took a long time (and numerous grammar packages) before I figured that mystery out...

**Comment by lierdakil** [comment]
So... any updates on this?

**Comment by Alhadis** [comment]
@50Wliu Any progress...?

**Comment by 50Wliu** [comment]
It doesn't look like my comment https://github.com/atom/grammar-selector/pull/34#issuecomment-309193384 has been addressed?

**Comment by Alhadis** [comment]
Uh no, because some grammars are intended to be assigned manually, or assigned [through programmatic means](https://github.com/Alhadis/language-file-magic/blob/master/index.js).

**Comment by Alhadis** [comment]
@50Wliu [Here's another example](https://github.com/Alhadis/language-roff/blob/f624022/grammars/output.cson) of a legitimate grammar that lacks a `fileType`. The intermediate output language generated by `troff` has no file extension, because it's intended to be piped between processes:

~~~shell
troff -Tps -man source.man | spool
~~~

However, anybody who's writing a Troff postprocessor will be thankful for the highlighting if they have to debug raw ditroff output:

~~~
x T pdf
x res 72000 1 1
x init
p1
V12000
H72000
DFd
wx font 5 TR
f5
s32000
h8000
v96000
md
tABC
wh8000
t`123'
wh8000
tXYZ
n12000 0
s10
f1
H0
s10
f1
V0
H720
V120
ch
50e44l28l28o50,w58w72o50r33l28dn120 0
x trailer
V7920
x stop
~~~

**Comment by Alhadis** [comment]
> This way TODO and hyperlink are hidden as well.

Hey wait a second, I forgot to ask... why is it critical that TODO and Hyperlink retain their `name` properties? If they're not seen in the grammar selection-list, then... what does it matter what they're called...?

**Comment by 50Wliu** [comment]
Because, uh, the tmbundle had it.  https://github.com/textmate/todo.tmbundle/blob/e77e5afc5c6b9d9387a1cbcc536755cead93e937/Syntaxes/TODO.tmLanguage#L9-L10 /shrug

So, anyway, `spec/fixtures/language-with-no-name/grammars/b.json` seems misleading because `b.json` does have a name.  Could you create a new fixtures folder instead?

**Comment by Alhadis** [comment]
What do you mean, _"create a new folder"_...? Don't you mean _"rename the current fixtures folder so the name is more accurate?"_

**Comment by 50Wliu** [comment]
No, because `a.json` is in fact missing a `name`.  I'm proposing the following folder structure:
```
- fixtures
  - language-with-no-name
    - grammars
      - a.json
  - language-with-a-name
    - grammars
      - b.json
```
Alternatively, do we even need `b.json`, given that all the other core languages have `name`?

**Comment by Alhadis** [comment]
> Alternatively, do we even need `b.json`, given that all the other core languages have `name`?

That's... actually a really good point. 😖 Will remove.

**Comment by Alhadis** [comment]
Done. The fact I didn't even need to modify a spec kinda proves how pointless that extra fixture was. 😀

**Comment by 50Wliu** [comment]
What happens when someone chooses a grammar without a name?  What does the Grammar Selector show in those scenarios, both in the modal panel and the status bar?

**Comment by Alhadis** [comment]
Nothing.

The status bar displays the `scopeName`:
Figure 1: Status Bar

The selector simply defaults to the top entry ("Auto detect"):
Figure 2: Grammar Selector

**Comment by lierdakil** [comment]
> What happens when someone chooses a grammar without a name? What does the Grammar Selector show in those scenarios, both in the modal panel and the status bar?

Isn't that a moot point though? How can someone select a grammar if it's not in grammar selector? Forcing it from code is an option, yes, but isn't the point of this whole PR that unnamed grammars aren't supposed to be used directly in TextEditor?

**Comment by Alhadis** [comment]
He was probably just checking to make sure there were no glaring anomalies in the UI when switching grammars programmatically. And I had to dig through code to remind myself how to set an editor's grammar the proper way (since the procedure for doing so has changed a number of times over the years... heh).

**Comment by Alhadis** [comment]
@50Wliu, I think it's safe to merge this. I've been using this fork for almost a year now, and so far I've spotted zero regressions, and zero UI oddities.

**Comment by Alhadis** [comment]
@50Wliu Anything I can do to move this along...?

**Comment by iolsen** [comment]
@50Wliu I'm fine with merging this if you want to shepherd that through.

**Comment by Alhadis** [comment]
Thank you so much!!! ❤️

**Comment by 50Wliu** [comment]
Thanks for creating the PR!

**Comment by Alhadis** [comment]
I'll be able to write a dedicated modelines package someday that encompasses both Emacs *and* Vim modelines, with injected highlighting that won't be listed in the selection list. :D

Emphasis on the word "someday". 😫

**Pull request merged**
